### ISSUE TITLE
About translate LaTex to AsciiMath

### ISSUE THREAD

**Issue by tomc14-cc** [belerico/py_asciimath#8]
for example,  py_asciimath "\[\bar{N}t=m{{v}_{0}}\sin \alpha\]" from latex to asciimath , it doesnt work.

**Comment by belerico** [comment]
I think that \bar is not in the defined LaTeX symbol in the latex.py file. Could you please add it in latex.py under the unary_functions dictionary as: 
```python
"\\overline": {
    "asciimath": ["bar", "overline"],
    "mathml": "<mover>{}<mo>&#x332;</mo></mover>",
},
```
Are there any error at all? Can you also run the translation with `log=True` and post the results?

**Comment by tomc14-cc** [comment]
great, it was fixed! i saw the LaTex of MathType keep the \bar as a key words.

**Comment by tomc14-cc** [comment]
fixed.
